### PR TITLE
feat: add power cables

### PR DESCRIPTION
**Pull request by ZayshaaCodes**
## Summary

Adds tiered power cables that move energy between Logistics engines, machines, and other Team Reborn Energy compatible blocks without turning the cable network into a hidden battery.

## Changes

- Adds Copper, Gold, and Ender Cables with 30/60/120 RF/t transfer tiers.
- Registers cable blocks, a shared cable block entity type, rubber mix/chunk items, recipes, loot tables, models, textures, and language entries.
- Adds per-level cable networks that rebuild lazily when cables are placed, removed, or neighbor connections change.
- Exposes cables as insert-only energy endpoints so push sources can deliver power through a network in the same transaction.
- Lets cable networks pull from ordinary extractable energy devices while skipping managed push sources such as engines, so engine output cadence stays authoritative.
- Adds cable probe output for tier transfer rate and connected machine demand.
- Adds dynamic chunk-baked cable rendering with connection-aware arms and device plugs for each tier.
- Adds cable-focused game tests plus a unit test for tier model naming.

## How it works

`CableBlock` owns placement, shape, waterlogging, connection invalidation, and probe entry points. It connects to adjacent `CableBlockEntity` instances as cable links and to any neighboring sided Team Reborn `EnergyStorage` that can insert or extract as a device link.

`CableBlockEntity` does not store energy. Its exposed `EnergyStorage` accepts insertion, reports zero stored energy/capacity, and forwards accepted energy to `CableNetworkManager` capped by the cable tier. If the connected consumers cannot accept the energy, the insertion returns `0` or a partial amount so the source keeps the remainder.

`CableNetworkManager` tracks cable positions per level, marks the graph dirty when topology changes, rebuilds networks with flood-fill, ticks networks once per server tick from the power domain, and clears level state on unload.

`CableNetwork` scans the cable graph boundary for connected energy devices. For normal network ticks it can move energy from extractable sources to insertable targets, but it skips `AbstractEngineBlockEntity` sources so engines continue pushing on their own schedule. For direct cable insertion, it excludes the source side, shuffles targets to avoid fixed directional bias, and uses Fabric transfer transactions so aborted transfers do not leak energy into consumers.

The client syncs a compact connection mask through the cable block entity. `CableModel` uses that mask as its geometry key, then emits the core, directional arms, single-ended nubs, and device plugs from the tier texture so visual connections match the server-side network state.

## Testing

- `./gradlew.bat test`
- `./gradlew.bat build` - includes 80 required game tests passing

### CODE REVIEW

**Comment by Indemnity83** [comment]
Really nice work here — the energy transfer logic, transaction handling, and network lifecycle management are all solid, and the game test coverage is comprehensive. I'm in a fix-only pre-release window right now so the merge is on hold, but this is queued up.

One small cleanup before I bring it in: `localTools/power-cable-ctm-lab.html` looks like a dev artifact from working out the CTM texture mapping. Happy to keep the Blockbench sources alongside the other models, but the HTML tool probably shouldn't live in the repo itself. Can you drop that file before we merge?

**Comment by ZayshaaCodes** [comment]
yep, will do, meant to localy git ignore that and forgot, there's also a glass.png in pipe resources that found its way in, i'll drop that also. i'll have a few more tweaks this afternoon

**Comment by Indemnity83** [comment]
Restructured the branch for the multiloader layout introduced in #318/#320. No logic changes — just moved files to the right places and fixed one bug that surfaced during compilation.

**File moves:**
- `src/main/java/...` → `common/src/main/java/...`
- `src/client/java/...` → `fabric/src/client/java/...`
- `src/gametest/java/...` → `fabric/src/gametest/java/...`
- `src/test/java/...` → `common/src/test/java/...`
- `src/main/resources/...` → `common/src/main/resources/...`

**Fabric API extraction:** `LogisticsPower` had Fabric-specific calls (`ServerTickEvents`, `ServerWorldEvents`, `ItemGroupEvents`) that can't live in common code. Moved those into `LogisticsFabric`.

**Bug fix:** `CreativeSinkBlockEntity` was missing its `EnergyDemandProvider` implementation (`networkDemandPerTick()`) and the transaction-aware `pendingInserts` tracking. The game tests were calling `sink.networkDemandPerTick()` so this was a compilation error. Ported the full implementation from the PR.

Build passes including game tests. Let me know if anything looks off.

**Comment by Indemnity83** [comment]
Merged manually via rebased branch (rebase/power-cables) onto updated mc/1.21.11 after the 15 refactoring commits. The squash commit 3acd7583 is now on mc/1.21.11. Thank you @ZayshaaCodes!
